"""add clients table, update vehicles owner

Revision ID: 871344d32821
Revises: d5c51f13f202
Create Date: 2026-03-30 20:19:41.238204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871344d32821'
down_revision: Union[str, Sequence[str], None] = 'd5c51f13f202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_constraint(op.f('vehicles_owner_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'clients', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_owner_id_fkey'), 'vehicles', 'users', ['owner_id'], ['id'])
    op.drop_table('clients')
    # ### end Alembic commands ###
