"""split address fields on clients

Revision ID: b262b7259d03
Revises: 871344d32821
Create Date: 2026-03-30 21:44:44.906451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b262b7259d03'
down_revision: Union[str, Sequence[str], None] = '871344d32821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('street_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('country', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('zip_code', sa.String(), nullable=True))
    op.drop_column('clients', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'zip_code')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'street_name')
    # ### end Alembic commands ###
