"""update vehicles add owner and timestamps to users

Revision ID: d5c51f13f202
Revises: 4d1aa48ffc29
Create Date: 2026-03-30 18:21:39.860684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c51f13f202'
down_revision: Union[str, Sequence[str], None] = '4d1aa48ffc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('make', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('odometer_km', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_tank_size', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('engine_oil', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('engine_oil_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('engine_oil_filter', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('transfer_case_oil', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('transfer_case_oil_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('diff_oil', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('diff_oil_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('transmission_oil', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('transmission_oil_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('power_steering_fluid', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('power_steering_fluid_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('brake_fluid', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('brake_fluid_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('coolant', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('coolant_capacity', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('vehicles', 'vin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vehicles', 'engine_displacement',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'vehicles', ['license_plate'])
    op.create_foreign_key(None, 'vehicles', 'users', ['owner_id'], ['id'])
    op.drop_column('vehicles', 'odometer')
    op.drop_column('vehicles', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('odometer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.alter_column('vehicles', 'engine_displacement',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('vehicles', 'vin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('vehicles', 'is_active')
    op.drop_column('vehicles', 'coolant_capacity')
    op.drop_column('vehicles', 'coolant')
    op.drop_column('vehicles', 'brake_fluid_capacity')
    op.drop_column('vehicles', 'brake_fluid')
    op.drop_column('vehicles', 'power_steering_fluid_capacity')
    op.drop_column('vehicles', 'power_steering_fluid')
    op.drop_column('vehicles', 'transmission_oil_capacity')
    op.drop_column('vehicles', 'transmission_oil')
    op.drop_column('vehicles', 'diff_oil_capacity')
    op.drop_column('vehicles', 'diff_oil')
    op.drop_column('vehicles', 'transfer_case_oil_capacity')
    op.drop_column('vehicles', 'transfer_case_oil')
    op.drop_column('vehicles', 'engine_oil_filter')
    op.drop_column('vehicles', 'engine_oil_capacity')
    op.drop_column('vehicles', 'engine_oil')
    op.drop_column('vehicles', 'fuel_tank_size')
    op.drop_column('vehicles', 'odometer_km')
    op.drop_column('vehicles', 'make')
    op.drop_column('vehicles', 'owner_id')
    # ### end Alembic commands ###
